[project]
name = "stands-agents-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-dotenv>=1.1.0",
    "strands-agents[litellm,ollama]>=0.1.7",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
